// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserServiceProto.proto

package com.rpc.dubbo.api.grpc;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rpc.dubbo.api.grpc.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
