// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserServiceProto.proto

package com.rpc.dubbo.api.grpc;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rpc.dubbo.api.grpc.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
