spring:
  application:
    name: dubbo-rpc-standard-boot-consumer-${spring.profiles.active}
  main:
    web-application-type: none
dubbo:
  application:
    qos-enable: false
    register-mode: instance
  registry:
    address: ${ZK_HOST:localhost}:2181
    protocol: zookeeper
  protocol:
    port: 9999
