spring:
  application:
    name: dubbo-rpc-standard-boot-consumer
  main:
    web-application-type: none
dubbo:
  application:
    qos-enable: false
  registry:
    address: zookeeper://${ZK_HOST:localhost}:2181
  protocol:
    port: 9999
