// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TripleGrpcProtocol.proto

// Protobuf Java Version: 3.25.5
package com.rpc.dubbo.api.proto;

public interface TripleGrpcProtocolServiceDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TripleGrpcProtocolServiceDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
