// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TripleGrpcProtocol.proto

// Protobuf Java Version: 3.25.5
package com.rpc.dubbo.api.proto;

public final class TripleGrpcProtocol {
  private TripleGrpcProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TripleGrpcProtocolServiceDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TripleGrpcProtocolServiceDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TripleGrpcProtocolServiceVO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TripleGrpcProtocolServiceVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030TripleGrpcProtocol.proto\",\n\034TripleGrpc" +
      "ProtocolServiceDTO\022\014\n\004name\030\001 \001(\t\"+\n\033Trip" +
      "leGrpcProtocolServiceVO\022\014\n\004name\030\001 \001(\t2y\n" +
      "\031TripleGrpcProtocolService\022\\\n\035testTriple" +
      "GrpcProtocolService\022\035.TripleGrpcProtocol" +
      "ServiceDTO\032\034.TripleGrpcProtocolServiceVO" +
      "B/\n\027com.rpc.dubbo.api.protoB\022TripleGrpcP" +
      "rotocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TripleGrpcProtocolServiceDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TripleGrpcProtocolServiceDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TripleGrpcProtocolServiceDTO_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_TripleGrpcProtocolServiceVO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TripleGrpcProtocolServiceVO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TripleGrpcProtocolServiceVO_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
