spring:
  application:
    name: dubbo-rpc-standard-boot-provider-${spring.profiles.active}
  main:
    web-application-type: none
dubbo:
  registry:
    # address: zookeeper://${ZK_HOST:127.0.0.1}:2181
    address: nacos://127.0.0.1:8848
    timeout: 3000
    register-mode: instance
  application:
    metadata-type: remote
