spring:
  application:
    name: dubbo-rpc-standard-boot-provider
dubbo:
  protocol:
    name: rest
    server: tomcat
    port: 8888
    contextpath: dubbo_rest_rpc
  registry:
    address: zookeeper://${ZK_HOST}:2181
    timeout: 30000
