spring:
  application:
    name: dubbo-rpc-standard-boot-provider
  main:
    web-application-type: none
dubbo:
  protocol:
    name: rest
    server: tomcat
    port: 8080
    contextpath: dubbo_rest_rpc
  registry:
    address: zookeeper://${ZK_HOST}:2181
    timeout: 3000
