spring:
  application:
    name: dubbo-rpc-standard-boot-provider-${spring.profiles.active}
  main:
    web-application-type: none
dubbo:
  registry:
    address: zookeeper://${ZK_HOST:127.0.0.1}:2181
    timeout: 3000
