# grpc 配置
grpc:
  server:
    port: 8888

spring:
  application:
    name: grpc-server
  main:
    web-application-type: servlet
# consul 配置
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
      enabled: true
      host: 192.168.4.81
      port: 8500
server:
  port: 9999
