grpc:
  server:
    port: 8888

spring:
  application:
    name: grpc-server
  main:
    web-application-type: servlet
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
server:
  port: 9999

# consul 配置